apiVersion: apps/v1
kind: Deployment
metadata:
  name: htyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app:htyu
  template:
    metadata:
      labels:
        app: htyu
    spec:
      containers:
      - image: okteto.dev/htyu:latest
        name: htyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "345c11b5-10df-47e9-8e5c-c0e1ac590c38"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "345c11b5-10df-47e9-8e5c-c0e1ac590c38"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
